### ISSUE TITLE
NW - [N3] - Ledger Integration

### ISSUE THREAD

**Issue by lllwvlvwlll** [CityOfZion/neon-wallet#2147]
This enhancement implements Ledger Nano S and X support for Neon desktop using a similar workflow as with Neo Legacy.  This feature is blocked by the Ledger Support initiative which is currently in-progress.

## Terms:
* Supported Hardware Wallets - Refers to the Ledger Nano S and Ledger Nano X hardware wallets
* Application - The Neon Wallet Desktop application

## Feature User Needs:
* UN01 - The user shall have the ability to authenticate into a Neo N3 account using the supported hardware wallets.
* UN02 - The authentication interface shall provide users with feedback on their authentication status.
* UN03 - The authentication interface shall provide users with their address upon application interfacing with the hardware wallet.
* UN04 - The authentication interface shall provide users with the option to create an additional address derived from the hardware wallet.
* UN05 - The application shall allow users to successfully sign and relay transactions for publishing on the Neo N3 blockchain.

### Authentication:
  <b>Test Begin State:</b> New ledger configuration without assets

 * [ ] 1. Navigate to the N3 side of the application and select "ledger" for the login method
 * [ ] 2. The "Connect and unlock your ledger device" has a spinner and login is disabled
 * [ ] 3. On the ledger, unlock the device with your pin
 * [ ] 4. On Neon Wallet, the authentication workflow should progress to the next step with a spinner
 * [ ] 5. Open the "Neo N3" app on the ledger device
 * [ ] 6. The "public address" field on Neon should be populated with an address
 * [ ] 7. Record the address
 * [ ] 8. Clicking the "dropdown chevron" presents the user with a single address
 * [ ] 9. Click the "fetch additional addresses" icon
 * [ ] 10. When clicking the dropdown chevron, the user is presented with a list of address options
 * [ ] 11. The login button is clickable
 * [ ] 12. Click the login button
 * [ ] 13. The user is taken into the application and the same address which was logged is presented to the user

### Transaction Signing
  <b>Test Begin State:</b>: Ledger Wallet using the same bip39 mnemonic as referenced in the Authentication test with N3 application installed and a non-zero GAS balance on the address logged in the previous test case.

 * [ ] 1. Navigate to the N3 side of the application and select "ledger" for the login method
 * [ ] 2. The "Connect and unlock your ledger device" has a spinner and login is disabled
 * [ ] 3. On the ledger, unlock the device with your pin
 * [ ] 4. On Neon Wallet, the authentication workflow should progress to the next step with a spinner
 * [ ] 5. Open the "Neo N3" app on the ledger device
 * [ ] 6. The "public address" field on Neon should be populated with the address 
 * [ ] 7. The login button is clickable
 * [ ] 8. Click the login button
 * [ ] 9. The user is taken into the application and the same address which was logged is presented to the user
 * [ ] 10. Verify that the expected non-zero GAS balance is presented
 * [ ] 11. Navigate to the `Send` tab and build a transaction to send 100% of the total GAS balance to another address
 * [ ] 12. Click the `Send` button
 * [ ] 13. Verify that there is a transaction request published on the ledger UI
 * [ ] 14. Sign the transaction on the ledger
 * [ ] 15. Navigate to the `Activity` tab and verify the the transaction has been minted to a block
 * [ ] 16. Navigate to the `Wallet` tab and verify that the account balance has been updated

### Transaction Signing (after timeout)
  <b>Test Begin State:</b>: Ledger Wallet using the same bip39 mnemonic as referenced in the Authentication test with N3 application installed and a non-zero GAS balance on the address logged in the previous test case.

 * [ ] 1. Navigate to the N3 side of the application and select "ledger" for the login method
 * [ ] 2. The "Connect and unlock your ledger device" has a spinner and login is disabled
 * [ ] 3. On the ledger, unlock the device with your pin
 * [ ] 4. On Neon Wallet, the authentication workflow should progress to the next step with a spinner
 * [ ] 5. Open the "Neo N3" app on the ledger device
 * [ ] 6. The "public address" field on Neon should be populated with the address 
 * [ ] 7. The login button is clickable
 * [ ] 8. Click the login button
 * [ ] 9. The user is taken into the application and the same address which was logged is presented to the user
 * [ ] 10. Verify that the expected non-zero GAS balance is presented
 * [ ] 11. Wait for the ledger to display its screensaver
 * [ ] 11. Navigate to the `Send` tab and build a transaction to send 100% of the total GAS balance to another address
 * [ ] 12. Verify that you are prompted to open the ledger app and sign the transaction
 * [ ] 13. Sign the transaction on the ledger
 * [ ] 14. Navigate to the `Activity` tab and verify the the transaction has been minted to a block
 * [ ] 15. Navigate to the `Wallet` tab and verify that the account balance has been updated

### Authentication and Signing using a `seed` passphrase
  <b>Test Begin State:</b> New ledger configuration without assets with an account configured using the advanced passphrase functionality of ledger: https://support.ledger.com/hc/en-us/articles/115005214529-Advanced-passphrase-security?docs=true

 * [ ] 1. Navigate to the N3 side of the application and select "ledger" for the login method
 * [ ] 2. The "Connect and unlock your ledger device" has a spinner and login is disabled
 * [ ] 3. On the ledger, unlock the device with your pin
 * [ ] 4. On Neon Wallet, the authentication workflow should progress to the next step with a spinner
 * [ ] 5. Open the "Neo N3" app on the ledger device
 * [ ] 6. The "public address" field on Neon should be populated with an address
 * [ ] 7. Record the address
 * [ ] 8. Clicking the "dropdown chevron" presents the user with a single address
 * [ ] 9. Click the "fetch additional addresses" icon
 * [ ] 10. When clicking the dropdown chevron, the user is presented with a list of address options
 * [ ] 11. The login button is clickable
 * [ ] 12. Click the login button
 * [ ] 13. The user is taken into the application and the same address which was logged is presented to the user

**Comment by rssavietto** [comment]
Hi @lllwvlvwlll I've tried finding the Ledger Support initiative issue on GitHub but I couldn't, do you have its number ? That way we can se it as a blocker for this one

**Comment by ixje** [comment]
@lllwvlvwlll To clarify; Is this supposed to co-exist with N2 ledger support? or is this to create a "one of" version that only supports N3 for passing the ledger review?

**Comment by lllwvlvwlll** [comment]
@ixje We need to enable the functionality in-parallel to the existing Legacy support. If you are able to add support to the authentication and signing features of the application, @comountainclimber will be able to intercept your work for the migration views.

**Comment by lllwvlvwlll** [comment]
resolved in v2.9.0
